# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Chvalotce Production Deployment

env:
  CHVALOTCE_SERVER_USERNAME: chvalotce-docker
  CHVALOTCE_SERVER_URL: chvalotce.cz
  HALLELUJAHHUB_SERVER_USERNAME: root
  HALLELUJAHHUB_SERVER_URL: 37.27.38.229
  DOCKER_IMAGE_NAME: worshiptool

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  upload-to-docker-chvalotce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Copy .env from remote server
        run: scp -o StrictHostKeyChecking=no "${{ env.SERVER_USERNAME }}@${{ env.SERVER_URL }}:/home/chvalotce.cz-docker/project-deploy/worshiptool/frontend/.env" ./.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest -t ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:chvalotce-prod .

      - name: Log Images
        run: docker images

      - name: Push
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:chvalotce-prod

  deploy-to-chvalotce:
    needs: upload-to-docker-chvalotce
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Redeploy application
        run: |
          ssh -o ServerAliveInterval=1000 "${SERVER_USERNAME}@${SERVER_URL}" "cd /home/chvalotce.cz-docker/project-deploy/worshiptool/frontend && bash ./redeploy.sh "
