# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: HallelujahHub Production Deployment

env:
  HALLELUJAHHUB_SERVER_USERNAME: root
  HALLELUJAHHUB_SERVER_URL: 37.27.38.229
  DOCKER_IMAGE_NAME: worshiptool

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  upload-to-docker-hallelujahhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HALLELUJAHHUB_SSH_KEY }}
          known_hosts: ${{ secrets.HALLELUJAHHUB_SSH_KNOWN_HOSTS }}

      - name: Copy .env from remote server
        run: scp -o StrictHostKeyChecking=no "${{ env.HALLELUJAHHUB_SERVER_USERNAME }}@${{ env.HALLELUJAHHUB_SERVER_URL }}:~/Workspace/worshiptool/hallelujahhub/frontend/.env" ./.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:hallelujahhub-prod .

      - name: Log Images
        run: docker images

      - name: Push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:hallelujahhub-prod

  deploy-to-hallelujahhub:
    needs: upload-to-docker-hallelujahhub
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HALLELUJAHHUB_SSH_KEY }}
          known_hosts: ${{ secrets.HALLELUJAHHUB_SSH_KNOWN_HOSTS }}

      - name: Redeploy application
        run: |
          ssh -o ServerAliveInterval=1000 "${{env.HALLELUJAHHUB_SERVER_USERNAME}}@${{env.HALLELUJAHHUB_SERVER_URL}}" "cd Workspace/worshiptool/hallelujahhub && bash ./redeploy.sh ./frontend"
  upload-to-docker-chwalmy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HALLELUJAHHUB_SSH_KEY }}
          known_hosts: ${{ secrets.HALLELUJAHHUB_SSH_KNOWN_HOSTS }}

      - name: Copy .env from remote server
        run: scp -o StrictHostKeyChecking=no "${{ env.HALLELUJAHHUB_SERVER_USERNAME }}@${{ env.HALLELUJAHHUB_SERVER_URL }}:~/Workspace/worshiptool/chwalmy/frontend/.env" ./.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:chwalmy-prod .

      - name: Log Images
        run: docker images

      - name: Push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:chwalmy-prod

  deploy-to-chwalmy:
    needs: upload-to-docker-chwalmy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HALLELUJAHHUB_SSH_KEY }}
          known_hosts: ${{ secrets.HALLELUJAHHUB_SSH_KNOWN_HOSTS }}

      - name: Redeploy application
        run: |
          ssh -o ServerAliveInterval=1000 "${{env.HALLELUJAHHUB_SERVER_USERNAME}}@${{env.HALLELUJAHHUB_SERVER_URL}}" "cd Workspace/worshiptool/chwalmy && bash ./redeploy.sh ./frontend"
